#!/bin/sh
FONT="Monospace"
SIZE=12
WIDTH=150
HEIGHT=30
XWINMOSAIC="xwinmosaic -r -f $FONT -s $SIZE -W $WIDTH -H $HEIGHT"

emacs_ls ()
{
    emacsclient --eval \
	'(mapconcat (quote (lambda (s) (format "%s" s)))
	    (remove-if (quote (lambda (name) (string= (substring name 0 1) " ")))
		       (mapcar (quote buffer-name) (buffer-list)))
		       "\n")' \
                           | xargs echo -e
}

emacs_sw ()
{
    emacs_ls | grep -x -F -q -e "$1" && \
        emacsclient -c --eval "(switch-to-buffer \"$1\")"
}

items=$(emacs_ls)

sel=$(echo "$items" | grep -v ^$ | sort -u | $XWINMOSAIC)
test -z "$sel" && exit 0 # 1?

emacs_sw $sel
