#!/bin/sh

emacs_ls ()
{
    emacsclient --eval \
	'(mapconcat (quote (lambda (s) (format "%s" s)))
	    (remove-if (quote (lambda (name) (string= (substring name 0 1) " ")))
		       (mapcar (quote buffer-name) (buffer-list)))
		       "\n")' \
                           | xargs echo -e
}

emacs_sw ()
{
    emacs_ls | grep -x -F -q -e "$1" && \
        emacsclient --eval "(switch-to-buffer \"$1\")"
}

items=$(emacs_ls)

sel=$(echo "$items" | grep -v ^$ | xwinmosaic -r)
test -z "$sel" && exit 0 # 1?

emacs_sw $sel
