#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/xwinmosaic_run
else
	cache=$HOME/.xwinmosaic_cache # if no xdg dir, fall back to dotfile in ~
fi
(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | xwinmosaic -r "$@"
	else
		xwinmosaic -r "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &
