#!/bin/sh

emacs_ls ()
{
    emacsclient --eval \
	'(mapconcat (quote (lambda (s) (format ", %s,%s,%s,%s"
                                 (get-color-name s)
                                 (get-icon-name s)
                                 s
                                 (get-buffer-mode-str s))))
                  (remove-if (quote (lambda (name) (string= (substring name 0 1) " ")))
                             (mapcar (quote buffer-name) (buffer-list)))
                  "\n")' \
                           | xargs echo -e
}

emacs_sw ()
{
    emacs_ls |awk -F',' '{ print $4 }'| grep -x -F -q -e "$1" && \
        emacsclient --eval "(switch-to-buffer \"$1\")"
}

items=$(emacs_ls)

sel=$(echo "$items" | grep -v ^$ | ~/src/xwinmosaic/build/src/xwinmosaic -rt $@)
test -z "$sel" && exit 0 # 1?

emacs_sw "$sel"
