#!/bin/sh

emacs_ls ()
{
    emacsclient --eval '(xwm-list-buffers)' | xargs echo -e
}

emacs_sw ()
{
    emacs_ls |awk -F',' '{ print $4 }'| grep -x -F -q -e "$1" && \
        emacsclient --eval "(switch-to-buffer \"$1\")"
}

items=$(emacs_ls)

sel=$(echo "$items" | grep -v ^$ | xwinmosaic -rt $@)
test -z "$sel" && exit 0

emacs_sw "$sel"
